### ISSUE TITLE
Style links in headers

### ISSUE THREAD

**Issue by slambert** [thec4aa/c4aa-org#70]
see: http://backtobasics.c4aa.org/what-we-do/

Let's start with:
- No underline
- text turns red on hover instead of all the time

And we'll see how that looks.

**Comment by zoracreates** [comment]
This is only a suggestion, but could these remain regular headings? I am not sure they need to be links since there are buttons under each section that lead to the same pages. It is a bit inconsistent with the rest of the website.

If they do remain as links, on the [News page](http://backtobasics.c4aa.org/category/news/), the :hover option for the titles (which are h2) is a dark gray (#4a4a4a). We should consider keeping this consistent. Would you like to try those red instead?

**Comment by slambert** [comment]
Yeah good point. If we link the headers it would just add to confusion we were already minimizing re: headers vs buttons.

Thank you!
